services:
  db:
    image: mysql:8.0
    env_file:
      - ./env
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  web:
    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "app/main.py"]
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./env

  
  
